### PR TITLE
Don't try to call tt when installing gem, it was broken anyways

### PR DESCRIPTION
**Pull request by kirillrdy**
This removes attempt to compile treetop files to ruby during gem installation

This is mainly to fix deployments to heroku, but there are also some other points to support this change

- its currently not working anyways, pattern for files in rake file is wrong, and tt binary doesn't set correct exit code when it fails to parse files, so that's why we didn't know it was broken.
- cant rely on binaries being in the path when we install gems, it seems to work in most cases, however bundler has an option `--deployment` which tells bundler to install gems in vendor location, thats why tt is not in the path when deploying to heroku

if we do infact want this, we would either use something that will guarantee tt is being installed during gem installation ( eg apt,gem,dnf install or for heroku some apt build pack) or we invoke treetop as a library ( might also be tricky to do during `bundle install` stage.

thoughts ?

### CODE REVIEW

**Comment by kirillrdy** [comment]
i guess its somewhat related, fixing the glob passed for treetop results in significant load time improvements ( my old laptop)
eg

broken: 
```
time ./afgen
real	0m1.779s
user	0m1.708s
sys	0m0.050s
```
precompiled:
```
./afgen
real	0m0.344s
user	0m0.310s
sys	0m0.031s
```

so maybe its worth fixing it,
maybe somehow add ruby files during gem files build stage rather than installation ?

**Comment by cjheath** [comment]
Although this was broken on Heroku, it was working everywhere else, basically forever.
I told you how this needed to be fixed (by changing the build procedure)... and now I've done that.
Just published a new gem made with the new build procedure.

**Comment by kirillrdy** [comment]
@cjheath can you point me to this new build procedure, because its seems to be broken for me locally ( not even heroku )

**Comment by cjheath** [comment]
See https://github.com/cjheath/activefacts-cql/blob/master/Rakefile#L8-L25
and https://github.com/cjheath/activefacts-cql/blob/master/activefacts-cql.gemspec#L20

**Pull request closed without merging**
